apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-devops-app
  template:
    metadata:
      labels:
        app: demo-devops-app
    spec:
      containers:
        - name: demo-devops-app
          image: dharma473/demo_devops_project:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
