apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-devops-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: demo-devops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-devops-service
            port:
              number: 80
