apiVersion: v1
kind: Service
metadata:
  # It's cleaner to use the include helper for the name
  name: {{ include "demo-devops.fullname" . }} 
  labels:
    {{- include "demo-devops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    # Selector should match the app label in deployment
    app: {{ include "demo-devops.fullname" . }} 
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      # Only include nodePort if the service type is NodePort
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }} 
      {{- end }}
